services:
  mailamator:
    build: .
    restart: unless-stopped
    volumes:
      - mailamator-data:/data
    environment:
      - MAILAMATOR_SECRET=${MAILAMATOR_SECRET}
      - MAILAMATOR_DB=/data/mailamator.db
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailamator.rule=Host(`mailamator.hippienet.wtf`)"
      - "traefik.http.routers.mailamator.entrypoints=websecure"
      - "traefik.http.routers.mailamator.tls.certresolver=letsencrypt"
      - "traefik.http.services.mailamator.loadbalancer.server.port=8080"

networks:
  frontend:
    external: true

volumes:
  mailamator-data:
